server:
  port: 9999
spring:
  application:
    name: tms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: pk3322486
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
#logging:
#  path: ${LOG_PATH:${LOG_TEMP:${java.io.tmpdir:/tmp}}}
#  file: ${logging.path}/app.log
#mybatis:
#  config-location: classpath:mybatis-config.xml
